server:
  port: 23001
  shutdown: graceful

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.0.6:3306/test?useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: root
    password: root12
  profiles:
    active: local
    group:
      local:
        - console-logging # 콘솔 로깅만 사용
      test:
        - console-logging
      prod:
        - console-logging
        - console-logging
    include:
      - console-logging
  application:
    name: broker
  kafka:
    producer:
      properties:
        min:
          insync:
            replicas: 2
  data:
    redis:
      cluster:
        max-redirects: 3
        connect-ip: 192.168.0.7
        nodes: 192.168.0.7:7000, 192.168.0.7:7001, 192.168.0.7:7002, 192.168.0.7:7003, 192.168.0.7:7004, 192.168.0.7:7005

kafka:
  bootstrapAddress: 192.168.0.3:6687
  admin:
    properties:
  topic:
    alarm:
      name: lawgg-alert
      replicationFactor: 1
      numPartitions: 1
  consumer:
    alarm:
      rdb-group-id: createAlarmInRDB
      redis-group-id: publishInRedis
    autoOffsetResetConfig: latest
  producer:
    acksConfig: all
    retry: 3
    enable-idempotence: true
    max-in-flight-requests-per-connection: 3